// tag::EN[]
[discrete]
=== Preparation
// end::EN[]

// --------------------------------------------------------------------

// tag::EN[]
[discrete]
==== Time and activities for trainer preparation
// end::EN[]

////
e.g, 10 min research and collect materials on the day before the session
////

// tag::EN[]
Setting up a course structure that works usually takes time and needs to be refined a few times based on experiences from trainings.
It is also never finished, as every given instance of a class gives you new insights and ideas on how to improve the training experience for your students.
// end::EN[]

// --------------------------------------------------------------------

// tag::EN[]
[discrete]
==== Time and activities for student preparation
// end::EN[]

////
e.g. 30 minutes 1 day in advance
////

// tag::EN[]
Students in this training are trainer candidates and should be familiar with the topics of the course in order to understand them from the meta level perspective needed to teach it.
This usually means they need theoretical knowledge and practical expertise in the topics covered by the course they are about to teach, which they might want to refresh by skim-reading seminal works you suggest.
Sometimes it is helpful to prepare with some of the teaching and didactics theory mentioned in the reference material above.
// end::EN[]

// --------------------------------------------------------------------

// tag::EN[]
[discrete]
==== Time for activity
// end::EN[]

////
e.g. 15 minutes shared discussion
////

// tag::EN[]
Trainer candidates should discuss set lengths, different training formats and different customer contexts that need adaptations, therefore some time for these discussions should be available.
// end::EN[]



// --------------------------------------------------------------------

// tag::EN[]
// [discrete]
// ==== Physical space required for activities
// end::EN[]

////
e.g. large room with 3 square meters per participant
////

// tag::EN[]
// TBD - CAN be provided - your content here
// end::EN[]

// --------------------------------------------------------------------

// tag::EN[]
// [discrete]
// ==== Physical materials required for activities 
// end::EN[]

////
e.g. whiteboard, flipchart, note-blocks, pencils
////

// tag::EN[]
// TBD - CAN be provided - your content here
// end::EN[]

// --------------------------------------------------------------------

// tag::EN[]
// [discrete]
// ==== Virtual material/infrastructure
// end::EN[]

////
e.g. shared whiteboard, shared text editor, … (possible alternatives). Mind possible constraints that have to be met, (e.g. max usage duration for tools, limits on number of participants)
////

// tag::EN[]
// TBD - CAN be provided - your content here
// end::EN[]

// --------------------------------------------------------------------

// tag::EN[]
// [discrete]
// ==== Prior knowledge of participants in the use of materials and infrastructure
// end::EN[]

////
e.g. must be confident in using the virtual whiteboard, soldering skills, …
////

// tag::EN[]
// TBD - CAN be provided - your content here
// end::EN[]

