// tag::EN[]
[discrete]
=== Success factors and risks
// end::EN[]

// --------------------------------------------------------------------

// tag::EN[]
[discrete]
==== General Risks
// end::EN[]

////
Fundamental disruptive factors (what could irritate, offend, trigger people about the topic, ....) e.g.:  could be interpreted as socially unacceptable behavior, racial prejudice, nationalism, religiously offending, ...
////

// tag::EN[]
TBD - CAN be provided - your content here
// end::EN[]

// --------------------------------------------------------------------


// tag::EN[]
[discrete]
==== Possible barriers to knowledge transfer
// end::EN[]

////
****
* Is this sending people in the wrong direction?
* Is there a danger of building up "false knowledge"? Is there a risk that, depending on the person of the trainer, the learners will not be able to acquire the knowledge? I.e. would they be able to do it in principle, but with certain trainers it does not work?
* (NOTE TO OURSELFES: This might be a more general high level topic)
* Have people possibly learned something different, a different background of experience or fundamentally different thought structures that prevent learners from coming to grips with the subject.
****
////

// tag::EN[]
TBD - CAN be provided - your content here
// end::EN[]

// --------------------------------------------------------------------

// tag::EN[]
// [discrete]
// ==== Success factors
// end::EN[]

////
* What contributes to the learning success?
* What are connections that lead out of the module? This might be things that motivate participants because what they have learned has greater practical value.
* How can LU success possibly be measured or determined (quantitatively/qualitatively)? "Definition of Done", not necessarily quantifiable: e.g. quizzes, exercise, role play, own presentation. 
////


// tag::EN[]
// TBD - CAN be provided - your content here
// end::EN[]

// --------------------------------------------------------------------
