= Curriculum for the https://isaqb.org[iSAQB] Train-the-Trainer Course

:toc:
:toc-placement!:

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Status
image:https://github.com/isaqb-org/curriculum-t3/workflows/CI%20-%20Releases%20and%20Main/badge.svg?branch=main["CI – Releases and Main"]
image:https://img.shields.io/github/last-commit/isaqb-org/curriculum-t3/main.svg["Last commit"]
image:https://img.shields.io/github/contributors/isaqb-org/curriculum-t3.svg["Contributors",link="https://github.com/isaqb-org/curriculum-t3/graphs/contributors"]
image:https://img.shields.io/github/issues/isaqb-org/curriculum-t3.svg["Issues",link="https://github.com/isaqb-org/curriculum-t3/issues"]
image:https://img.shields.io/github/issues-closed/isaqb-org/curriculum-t3.svg["Issues closed",link="https://github.com/isaqb-org/curriculum-t3/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+"]

This is <<copyrighted,copyrighted work>>.

== Content
This repository contains a very early work-in-progress version for the iSAQB Train-the-Trainer curriculum in AsciiDoc.

toc::[]

== How to contribute or participate
Create an issue or a pull-request

== How to use this repository

. Clone the repository - including the submodule:
+
--
[source,shell]
----
Via SSH:
git clone git@github.com:isaqb-org/curriculum-t3.git --recursive

Via HTTPS:
git clone https://github.com/isaqb-org/curriculum-t3.git --recursive
----
--
. Initialize (and possibly update) submodules with `git submodule init` and `git submodule update`.
. Build the project with http://www.gradle.com[gradle] (you need a locally installed JDK) via `./gradlew`.
. Once the "BUILD SUCCESSFUL" is shown, you can review the build result under `./build/index.html`


== Maintainers

This repository is currently maintained by the iSAQB Train-the-Trainer Working Group (T3WG).
It was forked from https://github.com/isaqb-org/advanced-template currently maintained by Benjamin Wolf, which in turn was forked from https://github.com/isaqb-org/curriculum-template,
so the contributors of those projects basically contributed to this one, too.


[[copyrighted]]
== Licensing and Copyright

include::license-copyright/LICENSE.adoc[]
