= Curriculum for the https://isaqb.org[iSAQB^®^] Train-the-Trainer Course

:toc:
:toc-placement!:

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Status
image:https://github.com/isaqb-org/curriculum-t3/workflows/CI%20-%20Releases%20and%20Main/badge.svg?branch=main["CI – Releases and Main"]
image:https://img.shields.io/github/last-commit/isaqb-org/curriculum-t3/main.svg["Last commit"]
image:https://img.shields.io/github/contributors/isaqb-org/curriculum-t3.svg["Contributors",link="https://github.com/isaqb-org/curriculum-t3/graphs/contributors"]
image:https://img.shields.io/github/issues/isaqb-org/curriculum-t3.svg["Issues",link="https://github.com/isaqb-org/curriculum-t3/issues"]
image:https://img.shields.io/github/issues-closed/isaqb-org/curriculum-t3.svg["Issues closed",link="https://github.com/isaqb-org/curriculum-t3/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+"]

This is <<copyrighted,copyrighted work>>.

== Content
This repository contains a very early work-in-progress version for the iSAQB^®^ Train-the-Trainer curriculum in AsciiDoc.

toc::[]

== How to contribute or participate
Create an issue or a pull-request.

== How to use this repository

. Clone the repository - including the submodule:
+
--
[source,shell]
----
Via SSH:
git clone git@github.com:isaqb-org/curriculum-t3.git --recursive

Via HTTPS:
git clone https://github.com/isaqb-org/curriculum-t3.git --recursive
----
--
. Initialize and update submodules with `git submodule init` and `git submodule update --recursive --remote`.
. Build the project with http://www.gradle.com[gradle] (You need a locally installed and current JDK, at least Java 17) via `./gradle-tools/gradlew`.
. Once the "BUILD SUCCESSFUL" is shown, you can review the build result under `./build/index.html`.

== On writing style

To keep writing style consistent across multiple iSAQB^®^ documents, please apply the styles used in the Foundation Level Curriculum.

=== Heading Capitalization

Use title case for all headings:

* capitalize: first and last word, nouns, pronouns, adjectives, verbs
* lowercase: articles and prepositions

When in doubt, opt for https://capitalizemytitle.com/style/Chicago/[Chicago Style].

=== Bullet Point Lists

To unify upper/lowercase within the (EN) version, we use the _Chicago manual of style proposal_":

* short bullet items don't get a full-stop
* next one starts lowercase
* if bullets are phrases or fragments, don't use punctuation
* if and only if an item is a really long sentence which deserves a full stop, or consists of several sentences, then we use it.
* Only then does an item start with uppercase.

For a possible German (DE) version, don't use punctuation at the end of bullet-list items, unless on the end of sentences.

=== Working with Feature Branches

TIP: If you've already made changes before branching, use `git stash` and `git stash pop` to temporarily store them.

==== Quick Start

. For existing issues use `Issue-#<number>-<Short-Description>` as the branch name
. Create and switch to feature branch:
+
--
[source,shell]
----
git checkout main
git pull
git checkout -b Issue-#42-add-examples    # or use your Git UI
----
--

. Make changes, commit and push
. Create pull request via GitHub web interface


==== Git UI Tools and Detailed Intructions

* Linux: https://sourcegit.dev/[SourceGit], https://www.gitkraken.com/[GitKraken]
* Windows/macOS: GitHub Desktop, VS Code
* All tools support basic branch & PR workflows
* GitHub guide: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests
* Git branching: https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging


== Maintainers

It was forked from https://github.com/isaqb-org/advanced-template currently maintained by Benjamin Wolf, which in turn was forked from https://github.com/isaqb-org/curriculum-template,
This repository is currently maintained by the iSAQB^®^ Train-the-Trainer Working Group (T3WG).
so the contributors of those projects basically contributed to this one, too.


[[copyrighted]]
== Licensing and Copyright

This is COPYRIGHTED work.

*(C) (Copyright), International Software Architecture Qualification Board e. V.
(iSAQB^(R)^ e. V.) 2024*

The curriculum may only be used subject to the following conditions:

1. You wish to obtain the CPSA Certified Professional for Software Architecture Foundation Level^(R)^ certificate or the CPSA Certified Professional for Software Architecture Advanced Level^(R)^ certificate.
For the purpose of obtaining the certificate, it shall be permitted to use these text documents and/or curricula
by creating working copies for your own computer. If any other use of documents and/or curricula is intended,
for instance for their dissemination to third parties, for advertising etc., please write to info@isaqb.org
to enquire whether this is permitted. A separate license agreement would then have to be entered into.
2. If you are a trainer or training provider, it shall be possible for you to use the documents
and/or curricula once you have obtained a usage license.
Please address any enquiries to info@isaqb.org. License agreements with comprehensive provisions for all aspects exist.
3. If you fall neither into category 1 nor category 2, but would like to use these documents and/or curricula nonetheless,
please also contact the iSAQB^®^ e. V. by writing to info@isaqb.org. You will then be informed about the possibility
of acquiring relevant licenses through existing license agreements, allowing you to obtain your desired usage authorizations.

We stress that, as a matter of principle, this curriculum is protected by copyright.
The International Software Architecture Qualification Board e. V. (iSAQB^(R)^ e. V.) has exclusive entitlement
to these copyrights.

The abbreviation "e. V." is part of the iSAQB's official name and stands for "eingetragener Verein" (registered association),
which describes its status as a legal entity according to German law.
For the purpose of simplicity, iSAQB^®^ e. V. shall hereafter be referred to as iSAQB^®^ without the use of said abbreviation.

