= Curriculum for the https://isaqb.org[iSAQB] Train-the-Trainer Course

:toc:
:toc-placement!:

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Status 
image:https://github.com/isaqb-org/curriculum-t3/workflows/CI%20-%20Releases%20and%20Main/badge.svg?branch=main["CI – Releases and Main"]
image:https://img.shields.io/github/last-commit/isaqb-org/curriculum-t3/main.svg["Last commit"]
image:https://img.shields.io/github/contributors/isaqb-org/curriculum-t3.svg["Contributors",link="https://github.com/isaqb-org/curriculum-t3/graphs/contributors"]
image:https://img.shields.io/github/issues/isaqb-org/curriculum-t3.svg["Issues",link="https://github.com/isaqb-org/curriculum-t3/issues"]
image:https://img.shields.io/github/issues-closed/isaqb-org/curriculum-t3.svg["Issues closed",link="https://github.com/isaqb-org/curriculum-t3/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+"]


This is <<copyrighted,copyrighted work>>.

== Content
This repository contains a very early work-in-progress version for the iSAQB Train-the-Trainer curriculum in AsciiDoc.

toc::[]

== How to contribute or participate
Create an issue, a merge- or pull-request

== How to use this repository

. Clone the repository - including the submodule:
+
--
[source,shell]
----
Via SSH:
git clone git@github.com:isaqb-org/curriculum-t3.git --recursive

Via HTTPS:
git clone https://github.com/isaqb-org/curriculum-t3.git --recursive
----
--
. Build the project with http://www.gradle.com[gradle] (you need a locally installed JDK) via `./gradlew`.
. Once the "BUILD SUCCESSFUL" is shown, you can review the build result under `./build/index.html`


=== How to organize files?

==== Prerequisite: AsciiDoc include
You should know some details about the AsciiDoc include statement.

If the Asciidoctor processor encounters a statement like the one below:

[source,asciidoc]
----
   include::directory/file.adoc[]
----

It will replace this include statement with the contents of `file.adoc`. That's easy and straightforward.

But there's more. We can tell AsciiDoc what parts of a file shall be included via the `tag` syntax. See below:

[source,asciidoc]
----
   include::directory/file.adoc[tags=X42]
----

Now AsciiDoctor will include everything from `file.adoc` which is contained between the opening and closing of tag `X42`. Let's look into our `file.adoc`:

[source,asciidoc]
----
some content that will be ignored...

   // tag::X42[]
   this content will be included with `include::directory/file.adoc[tags=X42]`
   // end::X42[]

and this content will be ignored again

   // tag::REMARK[]
   a comment from a reviewer that should be handled later
   // end::REMARK[]
----

You are thinking of using tags for i18n languages? Well done...


Now we're going one final step: We can enhance the include statement by *several* tags, so we can include multiple parts of a single file. I'll show the syntax and you know what I mean:

[source,asciidoc]
----
   include::directory/file.adoc[tags=X42;REMARK]
----

As you imagined, now both X42 and REMARK-tagged content will be included in the output.

=== Content and Structure files
As we are writing i18n we need to strictly distiguish between two
kind of files:

* *content* files, they contain text, tables or diagrams that shall be included in the output.
* *structure* files, containing only include-statements, configuration information. Structure files include both content-files and other structure files.

For content files, specific parts will be included via the tag-syntax described above.
For that purpose we define a variable named `include_configuration` in the file `config/setup.adoc`.

==== Structure File Example

In theory, you can just use the `docs/curriculum-template.adoc` as is and just
edit the section documents in the subdirectories. If you want to create your own file,
we recommend to stick with the following:

From `docs/curriculum-template.adoc` (excerpts):

[source,asciidoc]
----
= Template Curriculum: CPSA Certified Professional for Software Architecture^(R)^
:doctype: book

include::config/setup.adoc[]  // // <1>

:document-version: 2020.2 // //<2>

:sectnums!: // // <3>
include::00-preamble/copyright.adoc[{include_configuration}] // // <4>

<<< // // <5>
:toc:

<<<
:sectnums!:
include::00-preamble/00-introduction.adoc[] // //<6>

----

1. We propose to put the asciidoc configuration in this special file (`docs/config/setup.adoc`).
2. You can set a version, but it may be overridden in the build process.
3. You can turn section numbering on and off (here: off).
4. This includes parts of the `docs/00-preamble/copyright.adoc` file.
5. The `<<<` will create a pagebreak in pdf files.
6. Include the whole file 00-introduction.adoc.



== How to build the documents

Prerequisite: You need a Java Runtime(tm) installed.

You build the output documents with gradle.
That will produce both pdf and html output in German (DE) _and_ English (EN), unless you modify the configuration.

In case you want to change that, adjust the following part of `build.gradle`:

[source,groovy]
----
task buildDocs {
  group 'Documentation'
  description 'Grouping task for generating all languages in several formats'
  dependsOn "renderNoRemarksDE", "renderNoRemarksEN", "renderWithRemarksDE", "renderWithRemarksEN"
}
----

In the task "renderNoRemarksDE", certain attributes (aka variables) are defined that configure the corresponding output.


== Maintainers

This repository is currently maintained by the iSAQB Train-the-Trainer Working Group (T3WG).
It was forked from https://github.com/isaqb-org/advanced-template currently maintained by Benjamin Wolf, which in turn was forked from https://github.com/isaqb-org/curriculum-template,
so the contributors of those projects basically contributed to this one, too.


[[copyrighted]]
== Licensing and Copyright

include::license-copyright/LICENSE.adoc[]
