// tag::DE[]
== Einführung: Allgemeines zum Train-the-Trainer Kurs
// end::DE[]

// tag::EN[]
== Introduction: General information about the T3 course
// end::EN[]

// tag::EN[]
A Train-the-Trainer (T3) course is designed to enable trainers to efficiently and effectively deliver high-quality training content in iSAQB-accredited trainings.
It is primarily intended for trainers and prospective trainers who conduct or intend to conduct iSAQB CPSA Foundation-Level trainings, but will not exclude software architecture trainers at other levels from participating.
It focuses on enhancing expertise in the subject matter, effective teaching methods, creating a positive learning environment, and professional training delivery.
Participants learn to design and deliver engaging, high-quality courses, manage group dynamics, and handle challenging training situations.
The course also emphasizes continuous improvement and alignment with iSAQB values and standards.
While it enhances training delivery skills, it is not a prerequisite for trainer accreditation.
// end::EN[]

include::01-00-important-terms.adoc[{include_configuration}]

include::01-0X-rummage_box.adoc[{include_configuration}]

include::01-what-to-expect-of-a-t3-course.adoc[{include_configuration}]

include::02-t3-knowledge.adoc[{include_configuration}]

include::03-prerequisites-participants.adoc[{include_configuration}]

include::04-prerequisites-trainers.adoc[{include_configuration}]

// tag::REMARK[]
// just to get rid of a warning in the build process
// end::REMARK[]