// tag::EN[]

[discrete]
=== Rummage Box

[CAUTION]
====
This section contains all the the notes from "Competence Profile for iSAQB Trainers" document from nextcloud as well as from our confluence page concerning prerequsites. It should be inserted where appropriate and cleaned up. What doesn't fit should be deleted bit by bit but please retain the parts that need further discussion in the group, possibly merk them with a remarks-section.
====

[discrete]
==== Notes from NextCloud

_Draft by Alfredo Delgado Sanchez  and  Ralf Leipner_


_Comments by ALZ:_ Reduce and clarify - are those things that participants ...

* should already bring with them (prerequisites),
* are we going to train them or is this
* something they should work on afterwards?

e.g.: "This is a profile for those who are already iSAQB trainers." or "This is what you should be/become as a trainer.“

* Provide "scenarios" what do we mean by this competence,
* Ranking (before T3T, after T3T, long term importance)
* Provide Info on whether this is covered in the T3T.

Let's build a quality tree, operationalize it for motivating LUs.

[discrete]
===== 1. Subject matter competence

* The trainer is an expert and has knowledge of the subject matter.
* The trainer can refer to practical experience.
* The trainer practices continuously in his field of expertise.
* The trainer keeps himself informed about new trend and developments in the area of expertise.
* The trainer keeps his knowledge up to date. This is the solid basis of any training.
Without expert knowledge, the trainer cannot demonstrate confidence.
* The trainer should in broad have more expert knowledge than the participants.
* The trainer is sure which expertise is in high demand at the moment and can anticipate with a high probability what questions might be asked during the training.

[discrete]
===== 2. Methodical competence

* The trainer has a clear concept regarding the design and structuring of the course.
* The trainer is able to convey the content in an understandable way.
* The trainer knows the specifics of adult learning.
* The trainer is able to ensure the achievement of the learning objectives even for different learning types and qualification levels.
* The trainer designs a stimulating, varied and sustainable training.
* The trainer knows how to prepare learning content in a way that is suitable for the learners brain.
* The trainer uses different media appropriately.
* The trainer knows and uses different teaching methods and techniques.
* Trainers can constantly motivate course participants and keep their attention focused.
* The trainer knows how to communicate in an interesting, varied way.
* The trainer knows how to use body language and, if necessary, how to interpret the students' body language.


[discrete]
===== 3. Social competence

* The trainer is able to create a pleasant learning atmosphere.
* The trainer can optimally integrate the course participants into the teamwork.
* The trainer knows how group processes and group dynamics in general work.
* The trainer is able to recognize and resolve conflicts.
* The trainer knows how to deal with troublemakers.
* The trainer practices a professional feedback culture.
* The trainer is able to build a good relationship with the participants.

[discrete]
===== 4. Personality competence

* The trainer can motivate himself even in difficult situations.
* The trainer starts the training with a motivational kickoff for all participants.
* The trainer exudes confidence, professionalism and competence.
* The trainer also knows how to avoid and mitigate stress.
* The trainer uses his personal resources in the training in an optimal and balanced way?

[discrete]
==== Notes from Confluence

Migration of document https://confluence.isaqb.org/x/VQPhB



// end::EN[]


// tag::REMARK[]
// just to get rid of a warning in the build process
// end::REMARK[]