// tag::DE[]
=== Voraussetzungen zur Durchführung eines T3-Trainings
* erfolgreiche Ausbildung und Zertifizierung zum Certified Professional for Software Architecture, Foundation Level^(R)^ (CPSA-F)
* mindestens drei Jahre Vollzeit-Berufserfahrung in der IT-Branche; dabei Mitarbeit an Entwurf und Entwicklung von mindestens zwei unterschiedlichen IT-Systemen
** Ausnahmen sind auf Antrag zulässig (etwa: Mitarbeit in Open-Source-Projekten)
* Aus- und Weiterbildung im Rahmen von iSAQB-Advanced-Level-Schulungen im Umfang von mindestens 70 Credit Points aus mindestens drei unterschiedlichen Kompetenzbereichen
** bestehende Zertifizierungen (etwa Sun/Oracle Java-Architect, Microsoft CSA) können auf Antrag angerechnet werden
* erfolgreiche Bearbeitung der CPSA-A-Zertifizierungsprüfung

// end::DE[]

// tag::EN[]
=== Requirements for providing a T3 training
* Successful training and certification as a Certified Professional for Software Architecture, Foundation Level^(R)^ (CPSA-F)
* At least three years of full-time professional experience in the IT sector; collaboration on the design and development of at least two different IT systems
** Exceptions are allowed on application (e.g., collaboration on open source projects)
* Training and further education within the scope of iSAQB Advanced Level training courses with a minimum of 70 credit points from at least three different areas of competence
** existing certifications (for example: Sun/Oracle Java architect, Microsoft CSA) can be credited upon application
* Successful completion of the CPSA-A certification exam
// end::EN[]

// tag::REMARK[]
TODO, this is just the template from the advanced module.
// end::REMARK[]
