:sectnums!:

// tag::EN[]

[discrete]
=== Rummage Box

[CAUTION]
====
This section contains a lot of unsorted stuff from the original overview document from NextCloud. It should be inserted where appropriate and cleaned up. What doesn't fit should be deleted.
====

[discrete]
==== Notes from NextCloud

* Goals of this T3 training
* Terminology
* Difference between a foundation level training and a T3 training
* Target audience and contribution: The product/service iSAQB trainings deliver. Distinction: what makes iSAQB unique or why the audience should prefer it over another.
* Training tailored to the market: Trainers should understand their market (E.g., provide list of different target markets like automotive, telco, finance, ... and provide strategies on how to cope with their needs by e.g. using specialized/tailored examples and shifitng the focus of the training.
* What obligations does this put on the trainer and/or the training organization? Expected behavior and business practices of an iSAQB trainer
* Values and principle of iSAQB. Quality first.
* Workload on the trainer side, mental strength, self-talk regulation, relaxation methods, self-regulation techniques
* Further development of competencies as a trainer, e.g. advanced level and/or commication and presentation skills.
* Strategies for continuous improvement of the training

// end::EN[]

:sectnums:

// tag::REMARK[]
// just to get rid of a warning in the build process
// end::REMARK[]

