:sectnums!:

// tag::EN[]

[discrete]
=== Rummage Box

[CAUTION]
====
This section contains a lot of unsorted stuff from the original overview document from NextCloud. It should be inserted where appropriate and cleaned up. What doesn't fit should be deleted.
====

[discrete]
==== Notes from NextCloud

* Learning theory
** Specific challenges and peculiarities of adult learning in general. Overview of learning methods and learning effect
** Importance of learning objectives and benefit argumentation. Service value proposition and learner expectation
** Taxonomy levels according to Bloom
** Overview: Determine content, reduce content, structuring lessons (just a general overview, more details later in LU04)
** Attention in the classroom. Distraction factors. Learning performance of students throughout the day/course.
** Dealing with very heterogeneous group of participants with different skill levels and backgrounds. Training younger and/or less experienced participants
** How to handle incomplete/inconsistent knowledge and different perspectives on topics and concepts.

* Methods and techniques	
** Overview of different methods and concepts, e.g. 4Cs by Sharon Bowman
** Opening and closing methods
** How to use exercises, demos and case studies. (Overview only. More details on creating and using exercises in LU05). Short and simple exercises vs. complex scenarios, case studies, and continous exercixes. Advantages and disadvantages of both types of exercises
** Grouping participants for the exercises
** Feedback from the trainer, Evaluation of exercises, Feedback & Feedback Methods
** Giving and requesting feedback. Question methods, questionnaires, discussion rounds
** Feedback during Preparation and follow-up of a training (before and after the training and between training sessions)
** Objective evaluation of feedback by the participants
** Retro techniques 
** Education controlling & exam preparation, Checking knowledge
** Checking understanding and application: Validity, reliability and objectivity of exam questions
** Advantages and pitfalls of multiple-choice questions
** Ensure transfer of what has been learned into practice

* Communication and presentation skills 
** Interaction in the classroom, practical application of theory based on own cases and discussion in groups
** Activation of participants and improving learner engagement
** Non-constructive behavior, disturbances, indiscipline.
** Conflicts between participants. Conflict resolution.
** Best practices for handling "difficult" situations
** Basic rules of rhetoric, language in the classroom, dimensions of communication
** Stage fright
** Body language

* Media, tools and material
** use/creation of haptic media and teaching tools (flipchart, whiteboard)
** use/creation of digital media and teaching aids (PowerPoint,Survey Tools, Videos,)
** Collaboration and distance learning Tools (Teams, Zoom, digital Whiteboards (Miro), video/audio quality)
** how to anticipate and deal with technical issues, fallback infrastructure and communication channels, communication to participants during technical issues. 
** Handouts & accompanying material. Which documents should be given to the participants of the training?
** Recommending literature: Basic literature. What to read before the training. Additional material 
	
* Tips for first training (How to get started and do things right as a trainer in your first training).

// end::EN[]

:sectnums:

// tag::REMARK[]
// just to get rid of a warning in the build process
// end::REMARK[]

