// tag::EN[]
[discrete]
=== Didactics and Transfer
// end::EN[]

// --------------------------------------------------------------------

// tag::EN[]
[discrete]
==== Method Hints
// end::EN[]

////
Suggestions and recommendations for presenting the topic, ideas for exercises, and general hints for increasing student participation.  There is a Didaktopedia out there (for internal use), maybe we can reference it in the future.
////

// tag::EN[]
TBD - CAN be provided - your content here
// end::EN[]

// --------------------------------------------------------------------

// tag::EN[]
[discrete]
==== Previous Knowledge Regarding the Contents
// end::EN[]

////
e.g. learners should have finished LU xy, should know what pattern X is.
Note: this leads to constraints on the order of Learning Units!
////

// tag::EN[]
TBD - CAN be provided - your content here
// end::EN[]

// --------------------------------------------------------------------

// tag::EN[]
[discrete]
==== Sustaining Knowledge Transfer - Short Term
// end::EN[]

////
Follow-up activities: What do participants need to be able to independently follow up on the training session (additional material, links, literature references, videos, ....)? What things or artifacts can or should participants take home (screenshots, their own notes, photos of whiteboards, chat transcripts, ....)?
////

// tag::EN[]
TBD - CAN be provided - your content here
// end::EN[]

// --------------------------------------------------------------------

// tag::EN[]
[discrete]
==== Sustaining Knowledge Transfer - Long Term
// end::EN[]

////
Follow-up success control: How to check later, e.g. on subsequent days, if the content has been understood (e.g. warm-up exercise the next day, ....). How can this be verified after a longer period of time (e.g., offering a discussion session after several days, exam, term paper as in Advanced Level, ....)?
How can participants actually apply what they have learned. "How can I do $tuff."
////

// tag::EN[]
TBD - CAN be provided - your content here
// end::EN[]


