:sectnums!:

// tag::EN[]

[discrete]
=== Rummage  Box

[CAUTION]
====
This section contains a lot of unsorted stuff from the original word document and the overview from NextCloud. It should be inserted where apropriate. What not fits should be deleted.
====

[discrete]
==== Notes from NextCloud

_former LU 9. LU Designing and Evaluating Example Scenarios (Hiral Dave Alexander Lorz)_

* Purpose
** Enable trainers to provide a consistent example scenario throughout the course which fits the audience, that is it connects to their previous knowledge and delivers the learning goals of the FL curriculum.
** Enable trainers to evaluate the quality of example scenarios created or chosen by them.
	
* Learning objectives 
** T3 participants are able to Identify and present relevant example scenarios that help their students to understand the underlying concepts of software architecture.
** T3 participants can understand and describe the needs of their audience and from this knowledge derive audience-specific requirements on the example scenario(s) they are going to present.
** T3 participants should be able to explain the importance of having a consistent and high quality example scenario and also be able to verify or evaluate that their example meets the required quality standard.
** T3 participants should be able to explain the consequences of having unrelated example scenarios.
** T3P should come forward with a step by step list for creating or adapting scenarios to make them fit a specific set of learning objectives of the FL curriculum.
** T3P should be able to name possible sources for example scenarios.
	
_former LU 10. LU Creating Exercises based on an Example Scenario(Hiral Dave Alexander Lorz)_ +
(needs to be merged with everything that already exists in this LU)

* Purpose
** Enable trainers to create exercise aligned and connected to learning goals with a consideration to the overall schedule of the training
** Support trainers to choose the right type or methodology of exercise, depending on the content being covered and its place in the flow of the learning process.
** Support trainers to understand what to show with exercises depending on time constraints.
	
* Learning objectives 
	
** T3 participants are able to provide exercise to the students at the right time and at the right point in the content between the sessions and can explain the constraints on this.
** T3 participants are able to change between and to connect exercises and presentations considering the fixed training time.
** T3 participants are able to define what to show with the exercise, relate it to LG and delineate the expected outcome of the exercise. They are able to identify and name LGs that are covered with the specific exercise.
** T3P can break down an example scenario into single exercises and  identify gaps (Which LGs are not covered?).
** T3P can adapt exercises to fit the audience (e.g. level of difficulty, previous experience, etc.). For instance by adding tasks on the fly that increase the level of difficulty.
** T3P can identify showstoppers that keep students from being successful with the exercise and know how to overcome them (e.g. by providing specific detailed help).

[discrete]
==== Other Leftovers

* convey FL learning goals
* make it compelling, interesting
* people engage with the task and come up with insightful solutions 
* onstraints: required knowledge of the application domain of the example scenario
* complexity of the scenario  = required time to understand  scenario

* Trade-off: Simple scenarios take up less time to present but are not “deep” enough
Domain specific scenarios can build on previous knowledge and safe time - if they fit the domain of the audience and their knowledge level - but others might suffer.

Objective of this learning unit is, 
Trainer is able to design example scenarios such that participants are able to relate the important concepts of Software Architecture as a practical implementation. Example scenarios should address practical implementation of topics from CPSA-F training like Requirement to Design Goals, other design constraints, architecture method and explain the applied principles. Few listed below TBD:

1.	Stakeholders
2.	Risks
3.	Influencing factors
4.	Pattern choice
5.	Other design constraints
6.	Architecture method
7.  … maybe more, connect to FL LG’s make clear that you do not have to cover all of them

// end::EN[]

:sectnums:

// tag::REMARK[]
// just to get rid of a warning in the build process
// end::REMARK[]
