// tag::EN[]
[discrete]
=== Learning Objectives
// end::EN[]

// tag::REMARK[]
[sidebar]
The learning objective(s) that are covered by the LU. Try to formulate learning goals as a learning outcome by using the formula “Behavior + Concept or Skill = Learning Outcome” (see Bowman, Training from the Back of the room, chapter “Begin with the end”). E.g. “Future trainers can adapt a learning unit to the target audience and can explain the necessary adaptation steps.”
// end::REMARK[]

// tag::EN[]
[discrete]
[[LG-5-1]]
==== LG 5-1: Provide and present relevant example scenarios
T3 participants (T3P) are able to create or select relevant example scenarios that help their students to understand the underlying concepts of software architecture and can present those to their students.

[discrete]
[[LG-5-2]]
==== LG 5-2: Adapt example scenarios to participants and the curriculum
T3P can understand and describe the needs of their audience and from this understanding derive audience-specific requirements on the example scenario(s) they are going to present. To do so, they should be able to describe and apply the necessary steps for creating or adapting scenarios which aligns with their target group and a specific set of learning objectives of the FL curriculum.

[discrete]
[[LG-5-3]]
==== LG 5-3: Evaluate example scenarios
T3P should be able to explain the importance of having a consistent and high-quality example scenario and also be able to verify or evaluate that their example meets the required quality standard.
They also should be able to explain the consequences of mentioning unrelated example scenarios.

[discrete]
[[LG-5-4]]
==== LG 5-4: Know sources for example scenarios
T3P should be able to name possible sources for example scenarios (e.g. own experience or arc42 examples).

[discrete]
[[LG-5-5]]
==== LG 5-5:  Provide stand-alone exercises
T3P should be able to select, design and/or adapt exercises that

* support selected topics and LGs,
* adapt the didactic method,
* activates students’ participations
* facilitates understanding of relation to CPSA-F important LGs and delineate the expected outcome
* are covered at right context and within the timeline

// end::EN[]
