:sectnums!:
[discrete]
=== Rummage  Box

[CAUTION]
====
This section contains a lot of unsorted stuff from the original word document. It should be inserted wehre apropriate. What not fits should be deleted.
====

* convey FL learning goals
* make it compelling, interesting
* people engage with the task and come up with insightful solutions 
* onstraints: required knowledge of the application domain of the example scenario
* complexity of the scenario  = required time to understand  scenario

* Trade-off: Simple scenarios take up less time to present but are not “deep” enough
Domain specific scenarios can build on previous knowledge and safe time - if they fit the domain of the audience and their knowledge level - but others might suffer.

Objective of this learning unit is, 
Trainer is able to design example scenarios such that participants are able to relate the important concepts of Software Architecture as a practical implementation. Example scenarios should address practical implementation of topics from CPSA-F training like Requirement to Design Goals, other design constraints, architecture method and explain the applied principles. Few listed below TBD:

1.	Stakeholders
2.	Risks
3.	Influencing factors
4.	Pattern choice
5.	Other design constraints
6.	Architecture method
7.  … maybe more, connect to FL LG’s make clear that you do not have to cover all of them

:sectnums:
