// tag::EN[]
[discrete]
=== Learning Objectives
// end::EN[]

// tag::REMARK[]
[sidebar]
====
The learning objective(s) that are covered by the LU. Try to formulate learning goals as a learning outcome by using the formula “Behavior + Concept or Skill = Learning Outcome” (see Bowman, Training from the Back of the room, chapter “Begin with the end”). E. g. “Future trainers can adapt a learning unit to the target audience and can explain the necessary adaptation steps.”
====
// end::REMARK[]

// tag::EN[]
[[LG-1-1]]
==== LG 1-1: Provide and present relevant example scenarios
T3 participants are able to create or select relevant example scenarios that help their students to understand the underlying concepts of software architecture and can present those to their students.

[[LG-1-2]]
==== LG 1-2: Adapt example scenarios to participants and the curriculum
T3 participants can understand and describe the needs of their audience and from this knowledge derive audience-specific requirements on the example scenario(s) they are going to present. To do so, they should be able to describe and apply the necessary steps for creating or adapting scenarios to make them fit to their target group and a specific set of learning objectives of the FL curriculum.

[[LG-1-3]]
==== LG 1-3: Evaluate example scenarios
T3 participants should be able to explain the importance of having a consistent and high quality example scenario and also be able to verify or evaluate that their example meets the required quality standard. 
They also should be able to explain the consequences of having unrelated example scenarios.

[[LG-1-4]]
==== LG 1-4: Know sources for example scenarios
T3 participants should be able to name possible sources for example scenarios.
// end::EN[]
