// tag::DE[]
=== Gliederung des Lehrplans

Die einzelnen Abschnitte des Lehrplans sind gemäß folgender Gliederung beschrieben:

- **Begriffe/Konzepte**: Wesentliche Kernbegriffe dieses Themas.
- **Unterrichts-/Übungszeit**: Legt die Unterrichts- und Übungszeit fest, die für dieses Thema bzw. dessen Übung in einer akkreditierten Schulung mindestens aufgewendet werden muss.
- **Lernziele**: Beschreibt die zu vermittelnden Inhalte inklusive ihrer Kernbegriffe und -konzepte.

Dieser Abschnitt skizziert damit auch die zu erwerbenden Kenntnisse in entsprechenden Schulungen.
// end::DE[]

// tag::EN[]
=== Structure of Learning Units

Each LU always contains the following sections:

 * **Topic:** Coarse grained topic or learning area.
 * **Purpose:** The intention behind a LU.
 * **Learning Objectives:** A list of learning objectives or learning goals (LGs) that are covered by the LU. We strive to formulate learning goals as a learning outcome by using the formula "Behavior + Concept or Skill = Learning Outcome" according to <<bowman>>. 

LUs *may* contain additional sections describing takeaways for T3P, important discussion points, things to avoid when presenting the topic, references, and recommendations for didactics, knowledge transfer, and preparation.
If you would like to add or enhance these sections, please submit suggestions in the form of issues in the GitHub repository of the T3 curriculum <<tttgithub>>.

// end::EN[]