// tag::EN[]
[discrete]
=== Learning Objectives
// end::EN[]

// tag::REMARK[]
[sidebar]
The learning objective(s) that are covered by the LU. Try to formulate learning goals as a learning outcome by using the formula “Behavior + Concept or Skill = Learning Outcome” (see Bowman, Training from the Back of the room, chapter “Begin with the end”). E. g. “Future trainers can adapt a learning unit to the target audience and can explain the necessary adaptation steps.”
// end::REMARK[]

// tag::EN[]
[discrete]
[[LG-6-1]]

==== LG 6-1: Your first learning goal-Training management standards
T3P can describe how training providers organize trainings and can check if the organization of trainings adhere to iSAQBs best practices and standards and is within the legal framework given by iSAQB and is executed with ethical conduct.

They should be able to apply quality control of the standards if they work as a consultant to the training provider or as a training provider themselves, which includes understanding of accreditation of trainer and training provider, rules (likely training mode, group size etc), code of conduct. To summarize, T3P must understand-How does the accreditation process work (for training providers and trainers). 

- Licensing
- Rules 
- Codes of conduct
- Fees
- How does the accreditation process work (for training providers and trainers)


- What can be changed on the training/material
- contract, payment conditions
- Venue selection, Location, Group size limitation

* finding customers, registering participants, completing the iSAQB reporting requirements

*  "How to organize my business as trainer or training provider." (This is clearly out of scope for the training but this topic might come up and we should advise on how to handle this.)

* use of material
- Use and distribution of course material
* Contact point from iSAQB to get the slide deck notification and updates
* Contact point from iSAQB for any query related to training and training material as well as for overall work as a Training Provider and Trainer

Examination
* What to do when exams are not included in the training?

* Self-promotion" may need to be separated but would be enormously helpful for internationalization.
* iSAQB reporting requirements and fee reporting
* Announcing Trainings ( e.g. adding course dates to the iSAQB website)


[discrete]
[[LG-6-2]]
==== LG 6-2: Your second learning goal-Effective use of Intellectual Property
T3P can describe the effective use of licensed course material, which involves understanding its value, contract with iSAQB, payment conditions (new and for updates), limitations of amendments, distribution limitations and be aware of unauthorized use or infringement, 

[discrete]
[[LG-6-3]]
==== LG 6-3: Your third learning goal-Effective communication with iSAQB
T3P can explain about the iSAQB communication process for any query related to training and training material as well as for overall engagement as a training provider and trainer.
T3P can explain about the process to communicate with iSAQB GmbH for few facts which includes register as TP on iSAQB site, annual declaration of trainings, announcing the training dates and getting it listed on iSAQB official site, procuring the new slide deck, contact point from iSAQB to inquire for the updates of curriculum and foundation level course material, iSAQB reporting as TP & renewal requirements, understanding about Exam certifying partner and their role, promotions and available support.


// end::EN[]
